import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

type Character = {
  name: string,
  image: string,
  id: number
};

type info ={
  prev: string,
  next: string
}


export default function Home() {

  const [characters, setCharacters] = useState<Character[]>([]);
  const [currentPage, setCurrentPage] = useState("https://rickandmortyapi.com/api/character/?page=1")
  const [info, setInfo] = useState<info>({
    prev:"",
    next:""
  });

  useEffect( ()=>{
    fetch(currentPage)
    .then(response => response.json())
    .then(data => {
       setCharacters(data.results)
       setInfo(data.info)
    });
  }, [currentPage,info])

  return (
    <>
      <Head>
        <title>rick and morty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <h1>Rick and Morty</h1>
        <div>
          <button onClick={() =>setCurrentPage(info.prev)}>prev</button>
          <button onClick={() =>setCurrentPage(info.next)}>next</button>
        </div>
        <section>
          {characters.map((character)=>{
            return(
              <article key={character.name}>
                <Link href={`/character/${character.id}`}>
                  <h2>{character.name}</h2>
                  <img src={character.image} alt={character.name} />
                </Link>
              </article>
              )
            })}
        </section>
      </main>
    </>
  )
}
